//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Kauf
{
	public virtual object am
	{
		get;
		set;
	}

	public virtual object Menge
	{
		get;
		set;
	}

	public virtual object Preis
	{
		get;
		set;
	}

	public virtual Produkt Produkt
	{
		get;
		set;
	}

	public virtual Benutzer Benutzer
	{
		get;
		set;
	}

}

