//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Produkt
{
	public virtual object PID
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

	public virtual object Menge
	{
		get;
		set;
	}

	public virtual object PreisProEinheit
	{
		get;
		set;
	}

	public virtual Ebene Ebene
	{
		get;
		set;
	}

}

