//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Regal
{
	public virtual object RID
	{
		get;
		set;
	}

	public virtual object MaxEbene
	{
		get;
		set;
	}

	public virtual object Position
	{
		get;
		set;
	}

	public virtual Lager Lager
	{
		get;
		set;
	}

}

